from datetime import datetime
import requests, json
import pyinputplus as pyip

def date_num_generator():
    # get current microsecond value up to six decimal places
    current_time = datetime.now()
    x = current_time.microsecond 
    if x != 0:
        return (x)
    else:
        return 222222

def temp_num_generator():
    key_file = open('key.txt', 'r')
    api_key = key_file.readline().rstrip()
    key_file.close()
    # get temp in farenheit for rapid city, south dakota
    base_url = 'http://api.openweathermap.org/data/2.5/weather?id=5768233&appid='
    complete_url = base_url + api_key + '&units=imperial'
    response = requests.get(complete_url) 
    api = response.json()
    x = api['main']['temp']
    return x

def wind_num_generator():
    key_file = open('key.txt', 'r')
    api_key = key_file.readline().rstrip()
    key_file.close()
    # get wind speed in mph for buffalo, new york
    base_url = 'http://api.openweathermap.org/data/2.5/weather?id=5110629&appid='
    complete_url = base_url + api_key + '&units=imperial'
    response = requests.get(complete_url) 
    api = response.json()
    x = api['wind']['speed']
    return x

def generator():
    date_num = date_num_generator()
    temp_num = temp_num_generator()
    wind_num = wind_num_generator()
    # create new numbers by performing some equations on the values generated by the openweather API and from the current time  
    
    raw_num_1 = date_num * round(temp_num * date_num) * round(wind_num * date_num) * round(date_num * wind_num ** temp_num)
    raw_num_2 = date_num * round(temp_num * date_num) * round(wind_num * temp_num) * round(date_num * wind_num ** temp_num)
    raw_num_3 = date_num * round(temp_num * wind_num) * round(wind_num * date_num) * round(date_num * wind_num ** temp_num)
    raw_num_4 = date_num * round(date_num * wind_num) * round(wind_num * date_num) * round(temp_num * wind_num ** temp_num)
    # combine those new numbers into a single string
    full_num = str(raw_num_1) + str(raw_num_2) + str(raw_num_3) + str(raw_num_4)
    return full_num

def num_picker():
    full_num = generator()
    # variable to set length of final number
    range_choice = pyip.inputNum(greaterThan=0, lessThan=len(full_num), prompt=('[?] How many digits do you want to generate?: '))
    # flag to enable formatting for the final number
    format_num = pyip.inputYesNo(prompt=('[?] Do you want to use decimal separators? (e.g. 1,234,567,890) [Y/N]: '))
    if format_num == 'yes':
        formatted_num = f'{int(full_num[0:range_choice]):,}'
        print(formatted_num)
    else:
        print(full_num[0:range_choice])